# Generated by Django 2.2.7 on 2020-02-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
