# Generated by Django 2.2.7 on 2020-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(db_index=True, max_length=100)),
                ('userfirstname', models.CharField(db_index=True, max_length=100)),
                ('userlastname', models.CharField(db_index=True, max_length=100)),
                ('usercontact', models.CharField(db_index=True, max_length=100)),
                ('useremail', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('useraddressline1', models.CharField(db_index=True, max_length=100)),
                ('useraddressline2', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('userpicode', models.CharField(db_index=True, max_length=100)),
                ('note', models.TextField(db_index=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
