# Generated by Django 2.2.7 on 2020-02-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='userpicode',
            new_name='userpincode',
        ),
    ]
