# Generated by Django 2.2.7 on 2020-02-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liteorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='orders/%Y/%m/%d')),
                ('userfirstname', models.CharField(db_index=True, max_length=100)),
                ('userlastname', models.CharField(db_index=True, max_length=100)),
                ('usercontact', models.CharField(db_index=True, max_length=100)),
                ('useremail', models.CharField(db_index=True, max_length=100)),
                ('userpicode', models.CharField(db_index=True, max_length=100)),
                ('useraddress', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
