# Generated by Django 2.2.7 on 2020-02-15 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200205_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liteorder',
            old_name='useraddress',
            new_name='compneyname',
        ),
        migrations.RemoveField(
            model_name='liteorder',
            name='image',
        ),
        migrations.AddField(
            model_name='liteorder',
            name='city',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liteorder',
            name='county',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liteorder',
            name='note',
            field=models.TextField(db_index=True, default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liteorder',
            name='useraddressline1',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liteorder',
            name='useraddressline2',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
