# Generated by Django 2.2.7 on 2020-02-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200215_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liteorder',
        ),
    ]
