# Generated by Django 2.2.7 on 2020-02-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_liteorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfirstname', models.CharField(db_index=True, max_length=100)),
                ('userlastname', models.CharField(db_index=True, max_length=100)),
                ('compneyname', models.CharField(db_index=True, max_length=100)),
                ('usercontact', models.CharField(db_index=True, max_length=100)),
                ('useremail', models.CharField(db_index=True, max_length=100)),
                ('county', models.CharField(db_index=True, max_length=50)),
                ('useraddressline1', models.CharField(db_index=True, max_length=100)),
                ('useraddressline2', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('userpicode', models.CharField(db_index=True, max_length=100)),
                ('note', models.TextField(db_index=True, max_length=500)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
