# Generated by Django 2.2.7 on 2020-02-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productorder',
            new_name='Liteorder',
        ),
    ]
