# Generated by Django 2.2.7 on 2020-02-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200217_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liteorder',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/products/%Y/%m/%d'),
        ),
    ]
