# Generated by Django 2.2.7 on 2020-02-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200121_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
